# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBSCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserHasCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BBSCourse')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BBSUser')),
            ],
        ),
        migrations.AlterField(
            model_name='bbspost',
            name='P_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BBSUser'),
        ),
        migrations.AlterField(
            model_name='followuser',
            name='User1ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='web.BBSUser'),
        ),
        migrations.AlterField(
            model_name='userfollowpost',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BBSUser'),
        ),
        migrations.AlterField(
            model_name='userlikepost',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.BBSUser'),
        ),
    ]
