# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 12:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_auto_20161202_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbspost',
            name='P_Course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.BBSCourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bbsuser',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
